version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install awscli
  build:
    commands:
      - cd lambdas
      - zip ../index-photos.zip index-photos.py
      - zip ../search-photos.zip search-photos.py
      - cd ..
      - aws lambda update-function-code --function-name index-photos3 --zip-file fileb://index-photos.zip
      - aws lambda update-function-code --function-name search-photos3 --zip-file fileb://search-photos.zip
artifacts:
  files:
    - index-photos.zip
    - search-photos.zip
