version: 0.2

phases:
  build:
    commands:
      - cd lambdas
      - zip ../index-photos.zip index-photos.py
      - zip ../search-photos.zip search-photos.py
artifacts:
  files:
    - index-photos.zip
    - search-photos.zip
